<a href="https://colab.research.google.com/github/ramyanagavelli463-maker/N.Ramya/blob/main/Task_3_SQL_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv('/content/Amazon Sale Report.csv.zip', compression='zip')

print(df.head())
print(df.columns)
print(df.shape)

   index             Order ID      Date                        Status  \
0      0  405-8078784-5731545  04-30-22                     Cancelled
1      1  171-9198151-1101146  04-30-22  Shipped - Delivered to Buyer
2      2  404-0687676-7273146  04-30-22                       Shipped
3      3  403-9615377-8133951  04-30-22                     Cancelled
4      4  407-1069790-7240320  04-30-22                       Shipped

  Fulfilment Sales Channel  ship-service-level    Style              SKU  \
0   Merchant      Amazon.in           Standard   SET389   SET389-KR-NP-S
1   Merchant      Amazon.in           Standard  JNE3781  JNE3781-KR-XXXL
2     Amazon      Amazon.in          Expedited  JNE3371    JNE3371-KR-XL
3   Merchant      Amazon.in           Standard    J0341       J0341-DR-L
4     Amazon      Amazon.in          Expedited  JNE3671  JNE3671-TU-XXXL

        Category  ... currency  Amount    ship-city   ship-state  \
0            Set  ...      INR  647.62       MUMBAI  MAHARASHTRA
1          kurta  ...      INR  406.00    BENGALURU    KARNATAKA
2          kurta  ...      INR  329.00  NAVI MUMBAI  MAHARASHTRA
3  Western Dress  ...      INR  753.33   PUDUCHERRY   PUDUCHERRY
4            Top  ...      INR  574.00      CHENNAI   TAMIL NADU

  ship-postal-code  ship-country  \
0         400081.0            IN
1         560085.0            IN
2         410210.0            IN
3         605008.0            IN
4         600073.0            IN

                                       promotion-ids    B2B  fulfilled-by  \
0                                                NaN  False     Easy Ship
1  Amazon PLCC Free-Financing Universal Merchant ...  False     Easy Ship
2       IN Core Free Shipping 2015/04/08 23-48-5-108   True           NaN
3                                                NaN  False     Easy Ship
4                                                NaN  False           NaN

  Unnamed: 22
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN

[5 rows x 24 columns]
Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed: 22'],
      dtype='object')
(128975, 24)

/tmp/ipykernel_1384/3147592797.py:3: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/Amazon Sale Report.csv.zip', compression='zip')

In [ ]:
import zipfile
import pandas as pd

zip_path = '/content/Amazon Sale Report.csv.zip'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    print(zip_ref.namelist())

['Amazon Sale Report.csv']

In [ ]:
import zipfile
import pandas as pd

zip_path = '/content/Amazon Sale Report.csv.zip'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    csv_file = zip_ref.namelist()[0]
    df = pd.read_csv(zip_ref.open(csv_file))

print(df.head())
print(df.columns.tolist())
print(df.shape)

   index             Order ID      Date                        Status  \
0      0  405-8078784-5731545  04-30-22                     Cancelled
1      1  171-9198151-1101146  04-30-22  Shipped - Delivered to Buyer
2      2  404-0687676-7273146  04-30-22                       Shipped
3      3  403-9615377-8133951  04-30-22                     Cancelled
4      4  407-1069790-7240320  04-30-22                       Shipped

  Fulfilment Sales Channel  ship-service-level    Style              SKU  \
0   Merchant      Amazon.in           Standard   SET389   SET389-KR-NP-S
1   Merchant      Amazon.in           Standard  JNE3781  JNE3781-KR-XXXL
2     Amazon      Amazon.in          Expedited  JNE3371    JNE3371-KR-XL
3   Merchant      Amazon.in           Standard    J0341       J0341-DR-L
4     Amazon      Amazon.in          Expedited  JNE3671  JNE3671-TU-XXXL

        Category  ... currency  Amount    ship-city   ship-state  \
0            Set  ...      INR  647.62       MUMBAI  MAHARASHTRA
1          kurta  ...      INR  406.00    BENGALURU    KARNATAKA
2          kurta  ...      INR  329.00  NAVI MUMBAI  MAHARASHTRA
3  Western Dress  ...      INR  753.33   PUDUCHERRY   PUDUCHERRY
4            Top  ...      INR  574.00      CHENNAI   TAMIL NADU

  ship-postal-code  ship-country  \
0         400081.0            IN
1         560085.0            IN
2         410210.0            IN
3         605008.0            IN
4         600073.0            IN

                                       promotion-ids    B2B  fulfilled-by  \
0                                                NaN  False     Easy Ship
1  Amazon PLCC Free-Financing Universal Merchant ...  False     Easy Ship
2       IN Core Free Shipping 2015/04/08 23-48-5-108   True           NaN
3                                                NaN  False     Easy Ship
4                                                NaN  False           NaN

  Unnamed: 22
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN

[5 rows x 24 columns]
['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ', 'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN', 'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city', 'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids', 'B2B', 'fulfilled-by', 'Unnamed: 22']
(128975, 24)

/tmp/ipykernel_1384/898798836.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(zip_ref.open(csv_file))

In [ ]:
print(df.head())
print("\nColumns:")
print(df.columns.tolist())

print("\nShape:")
print(df.shape)

   index             Order ID      Date                        Status  \
0      0  405-8078784-5731545  04-30-22                     Cancelled
1      1  171-9198151-1101146  04-30-22  Shipped - Delivered to Buyer
2      2  404-0687676-7273146  04-30-22                       Shipped
3      3  403-9615377-8133951  04-30-22                     Cancelled
4      4  407-1069790-7240320  04-30-22                       Shipped

  Fulfilment Sales Channel  ship-service-level    Style              SKU  \
0   Merchant      Amazon.in           Standard   SET389   SET389-KR-NP-S
1   Merchant      Amazon.in           Standard  JNE3781  JNE3781-KR-XXXL
2     Amazon      Amazon.in          Expedited  JNE3371    JNE3371-KR-XL
3   Merchant      Amazon.in           Standard    J0341       J0341-DR-L
4     Amazon      Amazon.in          Expedited  JNE3671  JNE3671-TU-XXXL

        Category  ... currency  Amount    ship-city   ship-state  \
0            Set  ...      INR  647.62       MUMBAI  MAHARASHTRA
1          kurta  ...      INR  406.00    BENGALURU    KARNATAKA
2          kurta  ...      INR  329.00  NAVI MUMBAI  MAHARASHTRA
3  Western Dress  ...      INR  753.33   PUDUCHERRY   PUDUCHERRY
4            Top  ...      INR  574.00      CHENNAI   TAMIL NADU

  ship-postal-code  ship-country  \
0         400081.0            IN
1         560085.0            IN
2         410210.0            IN
3         605008.0            IN
4         600073.0            IN

                                       promotion-ids    B2B  fulfilled-by  \
0                                                NaN  False     Easy Ship
1  Amazon PLCC Free-Financing Universal Merchant ...  False     Easy Ship
2       IN Core Free Shipping 2015/04/08 23-48-5-108   True           NaN
3                                                NaN  False     Easy Ship
4                                                NaN  False           NaN

  Unnamed: 22
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN

[5 rows x 24 columns]

Columns:
['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ', 'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN', 'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city', 'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids', 'B2B', 'fulfilled-by', 'Unnamed: 22']

Shape:
(128975, 24)

In [ ]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)

print(df.columns.tolist())

['index', 'order_id', 'date', 'status', 'fulfilment', 'sales_channel', 'ship-service-level', 'style', 'sku', 'category', 'size', 'asin', 'courier_status', 'qty', 'currency', 'amount', 'ship-city', 'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids', 'b2b', 'fulfilled-by', 'unnamed:_22']

Order ID → order_id
Qty → qty
Amount → amount

In [ ]:
df['revenue'] = df['amount']

In [ ]:

import sqlite3

conn = sqlite3.connect('ecommerce.db')

df.to_sql(
    'ecommerce',
    conn,
    if_exists='replace',
    index=False
)

print("Database created successfully!")

Database created successfully!

In [ ]:
query = """
SELECT *
FROM ecommerce
LIMIT 10;
"""

pd.read_sql_query(query, conn)

,index,order_id,date,status,fulfilment,sales_channel,ship-service-level,style,sku,category,...,amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,b2b,fulfilled-by,unnamed:_22,revenue
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,None,0,Easy Ship,None,647.62
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,406.00
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,1,None,None,329.00
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,None,0,Easy Ship,None,753.33
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,574.00,CHENNAI,TAMIL NADU,600073.0,IN,None,0,None,None,574.00
5,5,404-1490984-4578765,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,...,824.00,GHAZIABAD,UTTAR PRADESH,201102.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,824.00
6,6,408-5748499-6859555,04-30-22,Shipped,Amazon,Amazon.in,Expedited,J0095,J0095-SET-L,Set,...,653.00,CHANDIGARH,CHANDIGARH,160036.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,653.00
7,7,406-7807733-3785945,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,kurta,...,399.00,HYDERABAD,TELANGANA,500032.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,399.00
8,8,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,...,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,NaN
9,9,402-4393761-0311520,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3461,JNE3461-KR-XXL,kurta,...,363.00,Chennai,TAMIL NADU,600041.0,IN,None,0,None,None,363.00

In [ ]:
query = """
SELECT *
FROM ecommerce
LIMIT 20;
"""

pd.read_sql_query(query, conn)

,index,order_id,date,status,fulfilment,sales_channel,ship-service-level,style,sku,category,...,amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,b2b,fulfilled-by,unnamed:_22,revenue
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,None,0,Easy Ship,None,647.62
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,406.00
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,1,None,None,329.00
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,None,0,Easy Ship,None,753.33
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,574.00,CHENNAI,TAMIL NADU,600073.0,IN,None,0,None,None,574.00
5,5,404-1490984-4578765,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,...,824.00,GHAZIABAD,UTTAR PRADESH,201102.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,824.00
6,6,408-5748499-6859555,04-30-22,Shipped,Amazon,Amazon.in,Expedited,J0095,J0095-SET-L,Set,...,653.00,CHANDIGARH,CHANDIGARH,160036.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,653.00
7,7,406-7807733-3785945,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,kurta,...,399.00,HYDERABAD,TELANGANA,500032.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,399.00
8,8,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,...,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,NaN
9,9,402-4393761-0311520,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3461,JNE3461-KR-XXL,kurta,...,363.00,Chennai,TAMIL NADU,600041.0,IN,None,0,None,None,363.00
10,10,407-5633625-6970741,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3160,JNE3160-KR-G-S,kurta,...,685.00,CHENNAI,TAMIL NADU,600073.0,IN,None,0,None,None,685.00
11,11,171-4638481-6326716,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3500,JNE3500-KR-XS,kurta,...,364.00,NOIDA,UTTAR PRADESH,201303.0,IN,None,0,None,None,364.00
12,12,405-5513694-8146768,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-XS,kurta,...,399.00,Amravati.,MAHARASHTRA,444606.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,399.00
13,13,408-7955685-3083534,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET182,SET182-KR-DH-XS,Set,...,657.00,MUMBAI,MAHARASHTRA,400053.0,IN,None,0,None,None,657.00
14,14,408-1298370-1920302,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,J0351,J0351-SET-L,Set,...,771.00,MUMBAI,MAHARASHTRA,400053.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,771.00
15,15,403-4965581-9520319,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,PJNE3368,PJNE3368-KR-6XL,kurta,...,544.00,GUNTAKAL,ANDHRA PRADESH,515801.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,544.00
16,16,406-9379318-6555504,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3721,JNE3721-KR-XXL,kurta,...,329.00,JAIPUR,RAJASTHAN,302020.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,329.00
17,17,405-9013803-8009918,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3405,JNE3405-KR-XL,kurta,...,399.00,NEW DELHI,DELHI,110074.0,IN,None,0,None,None,399.00
18,18,402-4030358-5835511,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3697,JNE3697-KR-XXL,kurta,...,458.00,Gurgaon,HARYANA,122004.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,458.00
19,19,405-5957858-1051546,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET254,SET254-KR-NP-XS,Set,...,886.00,BENGALURU,KARNATAKA,560017.0,IN,None,0,None,None,886.00

In [ ]:
query = """
SELECT *
FROM ecommerce
WHERE status = 'Shipped'
LIMIT 20;
"""

pd.read_sql_query(query, conn)

,index,order_id,date,status,fulfilment,sales_channel,ship-service-level,style,sku,category,...,amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,b2b,fulfilled-by,unnamed:_22,revenue
0,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,329.0,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,1,None,None,329.0
1,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,574.0,CHENNAI,TAMIL NADU,600073.0,IN,None,0,None,None,574.0
2,5,404-1490984-4578765,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,...,824.0,GHAZIABAD,UTTAR PRADESH,201102.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,824.0
3,6,408-5748499-6859555,04-30-22,Shipped,Amazon,Amazon.in,Expedited,J0095,J0095-SET-L,Set,...,653.0,CHANDIGARH,CHANDIGARH,160036.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,653.0
4,9,402-4393761-0311520,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3461,JNE3461-KR-XXL,kurta,...,363.0,Chennai,TAMIL NADU,600041.0,IN,None,0,None,None,363.0
5,10,407-5633625-6970741,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3160,JNE3160-KR-G-S,kurta,...,685.0,CHENNAI,TAMIL NADU,600073.0,IN,None,0,None,None,685.0
6,11,171-4638481-6326716,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3500,JNE3500-KR-XS,kurta,...,364.0,NOIDA,UTTAR PRADESH,201303.0,IN,None,0,None,None,364.0
7,13,408-7955685-3083534,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET182,SET182-KR-DH-XS,Set,...,657.0,MUMBAI,MAHARASHTRA,400053.0,IN,None,0,None,None,657.0
8,16,406-9379318-6555504,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3721,JNE3721-KR-XXL,kurta,...,329.0,JAIPUR,RAJASTHAN,302020.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,329.0
9,17,405-9013803-8009918,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3405,JNE3405-KR-XL,kurta,...,399.0,NEW DELHI,DELHI,110074.0,IN,None,0,None,None,399.0
10,19,405-5957858-1051546,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET254,SET254-KR-NP-XS,Set,...,886.0,BENGALURU,KARNATAKA,560017.0,IN,None,0,None,None,886.0
11,20,405-0607769-0716360,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3795,JNE3795-KR-XXXL,kurta,...,517.0,TIRUCHIRAPPALLI,TAMIL NADU,620018.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,517.0
12,21,404-8494550-5860325,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET345,SET345-KR-NP-M,Set,...,666.0,BENGALURU,KARNATAKA,560040.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,666.0
13,22,171-1305077-2813934,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3373,JNE3373-KR-L,kurta,...,376.0,HYDERABAD,TELANGANA,500072.0,IN,None,0,None,None,376.0
14,24,402-3384087-4005164,04-30-22,Shipped,Amazon,Amazon.in,Expedited,MEN5002,MEN5002-KR-L,kurta,...,499.0,TEZPUR,ASSAM,784001.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,499.0
15,27,408-3484251-6901959,04-30-22,Shipped,Amazon,Amazon.in,Expedited,PJNE2199,PJNE2199-KR-N-4XL,kurta,...,459.0,PUNE,MAHARASHTRA,411052.0,IN,None,0,None,None,459.0
16,28,405-7755803-4729935,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3567,JNE3567-KR-M,kurta,...,399.0,BENGALURU,KARNATAKA,560037.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,399.0
17,30,171-9040274-9291563,04-30-22,Shipped,Amazon,Amazon.in,Expedited,J0341,J0341-DR-S,Western Dress,...,791.0,THIRUVARUR,TAMIL NADU,613704.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,791.0
18,31,403-7056319-0979561,04-30-22,Shipped,Amazon,Amazon.in,Expedited,MEN5009,MEN5009-KR-XL,kurta,...,499.0,LUCKNOW,UTTAR PRADESH,226010.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,499.0
19,34,404-7774085-3780319,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3373,JNE3373-KR-XL,kurta,...,376.0,HYDERABAD,TELANGANA,500028.0,IN,None,0,None,None,376.0

In [ ]:
query = """
SELECT *
FROM ecommerce
ORDER BY revenue DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

,index,order_id,date,status,fulfilment,sales_channel,ship-service-level,style,sku,category,...,amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,b2b,fulfilled-by,unnamed:_22,revenue
0,42039,402-5239558-4281957,04-05-22,Shipped,Amazon,Amazon.in,Expedited,SET268,SET268-KR-NP-XS,Set,...,5584.00,GUNTUR,ANDHRA PRADESH,522007.0,IN,None,0,None,NaN,5584.00
1,11160,403-4106553-1691525,04-23-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,J0013,J0013-SKD-XXXL,Set,...,5495.00,JALANDHAR,PUNJAB,144022.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,1,Easy Ship,NaN,5495.00
2,24494,407-3483041-9133135,04-16-22,Cancelled,Merchant,Amazon.in,Standard,SET397,SET397-KR-NP -M,Set,...,4235.72,Jaipur,RAJASTHAN,302012.0,IN,None,0,Easy Ship,NaN,4235.72
3,89150,406-7195963-2374765,05-02-22,Shipped,Amazon,Amazon.in,Expedited,SET197,SET197-KR-NP-M,Set,...,3036.00,LUCKNOW,UTTAR PRADESH,226002.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,0.0,3036.00
4,121225,404-4712917-7300332,06-06-22,Shipped,Amazon,Amazon.in,Expedited,SET278,SET278-KR-NP-XXXL,Set,...,2894.00,MUMBAI,MAHARASHTRA,400081.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,0.0,2894.00
5,28814,408-9885439-6698733,04-13-22,Shipped,Amazon,Amazon.in,Expedited,J0285,J0285-SKD-S,Set,...,2864.00,BENGALURU,KARNATAKA,560032.0,IN,None,0,None,NaN,2864.00
6,39944,408-3363121-6123562,04-06-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3797,JNE3797-KR-XS,Western Dress,...,2860.00,KANPUR,UTTAR PRADESH,208001.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,NaN,2860.00
7,79899,405-6877720-7865168,05-07-22,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,JNE2086,JNE2086-KR-389-M,kurta,...,2796.00,MAHENDRAGARH,HARYANA,123029.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,0.0,2796.00
8,63974,408-9361250-7029128,05-19-22,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-XL,Set,...,2698.00,KOLKATA,WEST BENGAL,700016.0,IN,None,1,None,0.0,2698.00
9,75760,402-9141667-1791537,05-10-22,Cancelled,Amazon,Amazon.in,Expedited,SET364,SET364-KR-NP-XXL,Set,...,2676.00,CHENNAI,TAMIL NADU,600053.0,IN,None,0,None,0.0,2676.00

In [ ]:
query = """
SELECT category,
       SUM(revenue) AS total_revenue
FROM ecommerce
GROUP BY category
ORDER BY total_revenue DESC;
"""

pd.read_sql_query(query, conn)

        category  total_revenue
0            Set    39204124.03
1          kurta    21299546.70
2  Western Dress    11216072.69
3            Top     5347792.30
4   Ethnic Dress      791217.66
5         Blouse      458408.18
6         Bottom      150667.98
7          Saree      123933.76
8        Dupatta         915.00

In [ ]:
query = """
SELECT
    COUNT(*) AS total_records,
    SUM(revenue) AS total_revenue,
    AVG(revenue) AS average_revenue,
    MAX(revenue) AS maximum_revenue,
    MIN(revenue) AS minimum_revenue
FROM ecommerce;
"""

pd.read_sql_query(query, conn)

,total_records,total_revenue,average_revenue,maximum_revenue,minimum_revenue
0,128975,78592678.3,648.561465,5584.0,0.0

In [ ]:
print(df.columns.tolist())

['index', 'order_id', 'date', 'status', 'fulfilment', 'sales_channel', 'ship-service-level', 'style', 'sku', 'category', 'size', 'asin', 'courier_status', 'qty', 'currency', 'amount', 'ship-city', 'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids', 'b2b', 'fulfilled-by', 'unnamed:_22', 'revenue']

In [ ]:
query = """
SELECT order_id, category, qty, amount, status
FROM ecommerce
WHERE amount > 1000
LIMIT 20;
"""

pd.read_sql_query(query, conn)

               order_id category  qty   amount                        status
0   404-9632124-1107550      Set    1  1233.00  Shipped - Delivered to Buyer
1   408-3478480-0881162      Set    1  1126.00                       Shipped
2   408-3917043-5314763      Set    1  1146.00                       Shipped
3   408-7138000-9728362      Set    1  1033.00                       Shipped
4   405-6480932-8759528      Set    1  1146.00                       Shipped
5   408-4069830-3819562      Set    1  1281.00                       Shipped
6   408-4069830-3819562      Set    1  1186.00                       Shipped
7   404-6522553-9345930      Set    0  1105.36                     Cancelled
8   408-7698765-2294756      Set    1  1338.00  Shipped - Delivered to Buyer
9   406-0715107-8168308      Set    1  1186.00                       Shipped
10  405-9928526-2470747      Set    1  1115.00                       Shipped
11  171-0131752-2560336      Set    1  1399.00  Shipped - Delivered to Buyer
12  406-7779874-9136347      Set    1  1115.00                       Shipped
13  407-8801185-0134713      Set    1  1126.00                       Shipped
14  402-0048138-1845122      Set    1  1115.00                       Shipped
15  407-5875767-6399551      Set    1  1112.00                       Shipped
16  408-3874942-9917143      Set    1  1126.00                       Shipped
17  171-1851948-5476361      Set    1  1115.00                       Shipped
18  407-4936046-5852304      Set    0  1249.11                     Cancelled
19  407-4936046-5852304      Set    0  1058.93                     Cancelled

In [ ]:
query = """
SELECT order_id, category, qty, amount, revenue
FROM ecommerce
ORDER BY revenue DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

              order_id       category  qty   amount  revenue
0  402-5239558-4281957            Set    8  5584.00  5584.00
1  403-4106553-1691525            Set    5  5495.00  5495.00
2  407-3483041-9133135            Set    0  4235.72  4235.72
3  406-7195963-2374765            Set    4  3036.00  3036.00
4  404-4712917-7300332            Set    2  2894.00  2894.00
5  408-9885439-6698733            Set    2  2864.00  2864.00
6  408-3363121-6123562  Western Dress    4  2860.00  2860.00
7  405-6877720-7865168          kurta    4  2796.00  2796.00
8  408-9361250-7029128            Set    2  2698.00  2698.00
9  402-9141667-1791537            Set    2  2676.00  2676.00

In [ ]:
query = """
SELECT category,
       SUM(revenue) AS total_revenue
FROM ecommerce
GROUP BY category
ORDER BY total_revenue DESC;
"""

pd.read_sql_query(query, conn)

        category  total_revenue
0            Set    39204124.03
1          kurta    21299546.70
2  Western Dress    11216072.69
3            Top     5347792.30
4   Ethnic Dress      791217.66
5         Blouse      458408.18
6         Bottom      150667.98
7          Saree      123933.76
8        Dupatta         915.00

In [ ]:
query = """
SELECT category,
       AVG(revenue) AS average_revenue
FROM ecommerce
GROUP BY category
ORDER BY average_revenue DESC;
"""

pd.read_sql_query(query, conn)

        category  average_revenue
0            Set       833.385571
1          Saree       799.572645
2  Western Dress       762.790580
3   Ethnic Dress       723.895389
4            Top       526.098603
5         Blouse       520.327106
6          kurta       455.927108
7         Bottom       358.733286
8        Dupatta       305.000000

In [ ]:
query = """
SELECT status,
       COUNT(*) AS total_orders
FROM ecommerce
GROUP BY status
ORDER BY total_orders DESC;
"""

pd.read_sql_query(query, conn)

                           status  total_orders
0                         Shipped         77804
1    Shipped - Delivered to Buyer         28769
2                       Cancelled         18332
3    Shipped - Returned to Seller          1953
4             Shipped - Picked Up           973
5                         Pending           658
6   Pending - Waiting for Pick Up           281
7   Shipped - Returning to Seller           145
8      Shipped - Out for Delivery            35
9     Shipped - Rejected by Buyer            11
10                       Shipping             8
11      Shipped - Lost in Transit             5
12              Shipped - Damaged             1

In [ ]:
query = """
SELECT order_id,
       category,
       revenue
FROM ecommerce
WHERE revenue > (
    SELECT AVG(revenue)
    FROM ecommerce
)
ORDER BY revenue DESC
LIMIT 20;
"""

pd.read_sql_query(query, conn)

               order_id       category  revenue
0   402-5239558-4281957            Set  5584.00
1   403-4106553-1691525            Set  5495.00
2   407-3483041-9133135            Set  4235.72
3   406-7195963-2374765            Set  3036.00
4   404-4712917-7300332            Set  2894.00
5   408-9885439-6698733            Set  2864.00
6   408-3363121-6123562  Western Dress  2860.00
7   405-6877720-7865168          kurta  2796.00
8   408-9361250-7029128            Set  2698.00
9   402-9141667-1791537            Set  2676.00
10  403-0343365-3075550            Set  2664.00
11  171-9419863-7830701  Western Dress  2655.00
12  405-5657207-4685151            Set  2598.00
13  402-0603541-4663511            Set  2598.00
14  406-0207843-8044301            Set  2598.00
15  403-8890969-8669100            Set  2598.00
16  405-6605216-7124309            Set  2598.00
17  403-2726196-9752350            Set  2598.00
18  406-3360895-1639546            Set  2442.00
19  408-0398992-2545935            Set  2442.00

In [ ]:
query = """
CREATE VIEW category_revenue AS
SELECT category,
       SUM(revenue) AS total_revenue,
       AVG(revenue) AS average_revenue,
       COUNT(*) AS total_orders
FROM ecommerce
GROUP BY category;
"""

conn.execute(query)
conn.commit()

print("View created successfully!")

View created successfully!

In [ ]:
query = """
SELECT *
FROM category_revenue
ORDER BY total_revenue DESC;
"""

pd.read_sql_query(query, conn)

        category  total_revenue  average_revenue  total_orders
0            Set    39204124.03       833.385571         50284
1          kurta    21299546.70       455.927108         49877
2  Western Dress    11216072.69       762.790580         15500
3            Top     5347792.30       526.098603         10622
4   Ethnic Dress      791217.66       723.895389          1159
5         Blouse      458408.18       520.327106           926
6         Bottom      150667.98       358.733286           440
7          Saree      123933.76       799.572645           164
8        Dupatta         915.00       305.000000             3

In [ ]:
query = """
CREATE INDEX idx_order_id
ON ecommerce(order_id);
"""

conn.execute(query)
conn.commit()

print("Index created successfully!")

Index created successfully!

In [ ]:
query = """
SELECT *
FROM ecommerce
WHERE order_id = '405-8078784-5731545';
"""

pd.read_sql_query(query, conn)

,index,order_id,date,status,fulfilment,sales_channel,ship-service-level,style,sku,category,...,amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,b2b,fulfilled-by,unnamed:_22,revenue
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,None,0,Easy Ship,None,647.62

In [ ]:
df['order_id'].head()

0    405-8078784-5731545
1    171-9198151-1101146
2    404-0687676-7273146
3    403-9615377-8133951
4    407-1069790-7240320
Name: order_id, dtype: object

In [ ]:
customers = df[['order_id', 'ship-city', 'ship-state', 'ship-country']].drop_duplicates()

customers.to_sql(
    'customers',
    conn,
    if_exists='replace',
    index=False
)

print("Customers table created!")

Customers table created!

In [ ]:
query = """
SELECT e.order_id,
       e.category,
       e.revenue,
       c."ship-city",
       c."ship-state"
FROM ecommerce e
INNER JOIN customers c
ON e.order_id = c.order_id
LIMIT 20;
"""

pd.read_sql_query(query, conn)

               order_id       category  revenue    ship-city      ship-state
0   405-8078784-5731545            Set   647.62       MUMBAI     MAHARASHTRA
1   171-9198151-1101146          kurta   406.00    BENGALURU       KARNATAKA
2   404-0687676-7273146          kurta   329.00  NAVI MUMBAI     MAHARASHTRA
3   403-9615377-8133951  Western Dress   753.33   PUDUCHERRY      PUDUCHERRY
4   407-1069790-7240320            Top   574.00      CHENNAI      TAMIL NADU
5   404-1490984-4578765            Set   824.00    GHAZIABAD   UTTAR PRADESH
6   408-5748499-6859555            Set   653.00   CHANDIGARH      CHANDIGARH
7   406-7807733-3785945          kurta   399.00    HYDERABAD       TELANGANA
8   407-5443024-5233168            Set      NaN    HYDERABAD       TELANGANA
9   402-4393761-0311520          kurta   363.00      Chennai      TAMIL NADU
10  407-5633625-6970741          kurta   685.00      CHENNAI      TAMIL NADU
11  171-4638481-6326716          kurta   364.00        NOIDA   UTTAR PRADESH
12  405-5513694-8146768          kurta   399.00    Amravati.     MAHARASHTRA
13  408-7955685-3083534            Set   657.00       MUMBAI     MAHARASHTRA
14  408-1298370-1920302            Set   771.00       MUMBAI     MAHARASHTRA
15  403-4965581-9520319          kurta   544.00     GUNTAKAL  ANDHRA PRADESH
16  406-9379318-6555504          kurta   329.00       JAIPUR       RAJASTHAN
17  405-9013803-8009918          kurta   399.00    NEW DELHI           DELHI
18  402-4030358-5835511          kurta   458.00      Gurgaon         HARYANA
19  405-5957858-1051546            Set   886.00    BENGALURU       KARNATAKA

In [ ]:
query = """
SELECT e.order_id,
       e.category,
       e.revenue,
       c."ship-city",
       c."ship-state"
FROM ecommerce e
LEFT JOIN customers c
ON e.order_id = c.order_id
LIMIT 20;
"""

pd.read_sql_query(query, conn)

               order_id       category  revenue    ship-city      ship-state
0   405-8078784-5731545            Set   647.62       MUMBAI     MAHARASHTRA
1   171-9198151-1101146          kurta   406.00    BENGALURU       KARNATAKA
2   404-0687676-7273146          kurta   329.00  NAVI MUMBAI     MAHARASHTRA
3   403-9615377-8133951  Western Dress   753.33   PUDUCHERRY      PUDUCHERRY
4   407-1069790-7240320            Top   574.00      CHENNAI      TAMIL NADU
5   404-1490984-4578765            Set   824.00    GHAZIABAD   UTTAR PRADESH
6   408-5748499-6859555            Set   653.00   CHANDIGARH      CHANDIGARH
7   406-7807733-3785945          kurta   399.00    HYDERABAD       TELANGANA
8   407-5443024-5233168            Set      NaN    HYDERABAD       TELANGANA
9   402-4393761-0311520          kurta   363.00      Chennai      TAMIL NADU
10  407-5633625-6970741          kurta   685.00      CHENNAI      TAMIL NADU
11  171-4638481-6326716          kurta   364.00        NOIDA   UTTAR PRADESH
12  405-5513694-8146768          kurta   399.00    Amravati.     MAHARASHTRA
13  408-7955685-3083534            Set   657.00       MUMBAI     MAHARASHTRA
14  408-1298370-1920302            Set   771.00       MUMBAI     MAHARASHTRA
15  403-4965581-9520319          kurta   544.00     GUNTAKAL  ANDHRA PRADESH
16  406-9379318-6555504          kurta   329.00       JAIPUR       RAJASTHAN
17  405-9013803-8009918          kurta   399.00    NEW DELHI           DELHI
18  402-4030358-5835511          kurta   458.00      Gurgaon         HARYANA
19  405-5957858-1051546            Set   886.00    BENGALURU       KARNATAKA

In [ ]:
print("Task 3 SQL analysis completed successfully!")

Task 3 SQL analysis completed successfully!

In [ ]:
sql_code = """
-- Task 3: SQL for Data Analysis
-- E-commerce Sales Analysis

-- 1. SELECT
SELECT *
FROM ecommerce
LIMIT 20;

-- 2. WHERE
SELECT order_id, category, qty, amount, status
FROM ecommerce
WHERE amount > 1000
LIMIT 20;

-- 3. ORDER BY
SELECT order_id, category, qty, amount, revenue
FROM ecommerce
ORDER BY revenue DESC
LIMIT 10;

-- 4. GROUP BY
SELECT category,
       SUM(revenue) AS total_revenue
FROM ecommerce
GROUP BY category
ORDER BY total_revenue DESC;

-- 5. Aggregate Functions
SELECT
    COUNT(*) AS total_records,
    SUM(revenue) AS total_revenue,
    AVG(revenue) AS average_revenue,
    MAX(revenue) AS maximum_revenue,
    MIN(revenue) AS minimum_revenue
FROM ecommerce;

-- 6. Average Revenue by Category
SELECT category,
       AVG(revenue) AS average_revenue
FROM ecommerce
GROUP BY category
ORDER BY average_revenue DESC;

-- 7. Count Orders by Status
SELECT status,
       COUNT(*) AS total_orders
FROM ecommerce
GROUP BY status
ORDER BY total_orders DESC;

-- 8. Subquery
SELECT order_id,
       category,
       revenue
FROM ecommerce
WHERE revenue > (
    SELECT AVG(revenue)
    FROM ecommerce
)
ORDER BY revenue DESC
LIMIT 20;

-- 9. Create View
CREATE VIEW category_revenue AS
SELECT category,
       SUM(revenue) AS total_revenue,
       AVG(revenue) AS average_revenue,
       COUNT(*) AS total_orders
FROM ecommerce
GROUP BY category;

-- 10. Use View
SELECT *
FROM category_revenue
ORDER BY total_revenue DESC;

-- 11. Create Index
CREATE INDEX idx_order_id
ON ecommerce(order_id);

-- 12. INNER JOIN
SELECT e.order_id,
       e.category,
       e.revenue,
       c."ship-city",
       c."ship-state"
FROM ecommerce e
INNER JOIN customers c
ON e.order_id = c.order_id
LIMIT 20;

-- 13. LEFT JOIN
SELECT e.order_id,
       e.category,
       e.revenue,
       c."ship-city",
       c."ship-state"
FROM ecommerce e
LEFT JOIN customers c
ON e.order_id = c.order_id
LIMIT 20;
"""

with open("ecommerce_queries.sql", "w") as f:
    f.write(sql_code)

print("ecommerce_queries.sql created successfully!")

ecommerce_queries.sql created successfully!

In [ ]:
from google.colab import files

files.download("ecommerce_queries.sql")

In [ ]:
query = """
SELECT *
FROM ecommerce
LIMIT 20;
"""

pd.read_sql_query(query, conn)

,index,order_id,date,status,fulfilment,sales_channel,ship-service-level,style,sku,category,...,amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,b2b,fulfilled-by,unnamed:_22,revenue
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,None,0,Easy Ship,None,647.62
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,406.00
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,1,None,None,329.00
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,None,0,Easy Ship,None,753.33
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,574.00,CHENNAI,TAMIL NADU,600073.0,IN,None,0,None,None,574.00
5,5,404-1490984-4578765,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,...,824.00,GHAZIABAD,UTTAR PRADESH,201102.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,824.00
6,6,408-5748499-6859555,04-30-22,Shipped,Amazon,Amazon.in,Expedited,J0095,J0095-SET-L,Set,...,653.00,CHANDIGARH,CHANDIGARH,160036.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,653.00
7,7,406-7807733-3785945,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,kurta,...,399.00,HYDERABAD,TELANGANA,500032.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,399.00
8,8,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,...,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,NaN
9,9,402-4393761-0311520,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3461,JNE3461-KR-XXL,kurta,...,363.00,Chennai,TAMIL NADU,600041.0,IN,None,0,None,None,363.00
10,10,407-5633625-6970741,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3160,JNE3160-KR-G-S,kurta,...,685.00,CHENNAI,TAMIL NADU,600073.0,IN,None,0,None,None,685.00
11,11,171-4638481-6326716,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3500,JNE3500-KR-XS,kurta,...,364.00,NOIDA,UTTAR PRADESH,201303.0,IN,None,0,None,None,364.00
12,12,405-5513694-8146768,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-XS,kurta,...,399.00,Amravati.,MAHARASHTRA,444606.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,399.00
13,13,408-7955685-3083534,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET182,SET182-KR-DH-XS,Set,...,657.00,MUMBAI,MAHARASHTRA,400053.0,IN,None,0,None,None,657.00
14,14,408-1298370-1920302,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,J0351,J0351-SET-L,Set,...,771.00,MUMBAI,MAHARASHTRA,400053.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,771.00
15,15,403-4965581-9520319,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,PJNE3368,PJNE3368-KR-6XL,kurta,...,544.00,GUNTAKAL,ANDHRA PRADESH,515801.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,544.00
16,16,406-9379318-6555504,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3721,JNE3721-KR-XXL,kurta,...,329.00,JAIPUR,RAJASTHAN,302020.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,329.00
17,17,405-9013803-8009918,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3405,JNE3405-KR-XL,kurta,...,399.00,NEW DELHI,DELHI,110074.0,IN,None,0,None,None,399.00
18,18,402-4030358-5835511,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3697,JNE3697-KR-XXL,kurta,...,458.00,Gurgaon,HARYANA,122004.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,458.00
19,19,405-5957858-1051546,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET254,SET254-KR-NP-XS,Set,...,886.00,BENGALURU,KARNATAKA,560017.0,IN,None,0,None,None,886.00

Desktop
→ Task-3-SQL-Data-Analysis
→ screenshots

select.png

In [ ]:
query = """
SELECT *
FROM ecommerce
LIMIT 20;
"""

pd.read_sql_query(query, conn)

,index,order_id,date,status,fulfilment,sales_channel,ship-service-level,style,sku,category,...,amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,b2b,fulfilled-by,unnamed:_22,revenue
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,None,0,Easy Ship,None,647.62
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,406.00
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,1,None,None,329.00
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,None,0,Easy Ship,None,753.33
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,574.00,CHENNAI,TAMIL NADU,600073.0,IN,None,0,None,None,574.00
5,5,404-1490984-4578765,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,...,824.00,GHAZIABAD,UTTAR PRADESH,201102.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,824.00
6,6,408-5748499-6859555,04-30-22,Shipped,Amazon,Amazon.in,Expedited,J0095,J0095-SET-L,Set,...,653.00,CHANDIGARH,CHANDIGARH,160036.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,653.00
7,7,406-7807733-3785945,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,kurta,...,399.00,HYDERABAD,TELANGANA,500032.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,399.00
8,8,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,...,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,NaN
9,9,402-4393761-0311520,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3461,JNE3461-KR-XXL,kurta,...,363.00,Chennai,TAMIL NADU,600041.0,IN,None,0,None,None,363.00
10,10,407-5633625-6970741,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3160,JNE3160-KR-G-S,kurta,...,685.00,CHENNAI,TAMIL NADU,600073.0,IN,None,0,None,None,685.00
11,11,171-4638481-6326716,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3500,JNE3500-KR-XS,kurta,...,364.00,NOIDA,UTTAR PRADESH,201303.0,IN,None,0,None,None,364.00
12,12,405-5513694-8146768,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-XS,kurta,...,399.00,Amravati.,MAHARASHTRA,444606.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,399.00
13,13,408-7955685-3083534,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET182,SET182-KR-DH-XS,Set,...,657.00,MUMBAI,MAHARASHTRA,400053.0,IN,None,0,None,None,657.00
14,14,408-1298370-1920302,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,J0351,J0351-SET-L,Set,...,771.00,MUMBAI,MAHARASHTRA,400053.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,771.00
15,15,403-4965581-9520319,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,PJNE3368,PJNE3368-KR-6XL,kurta,...,544.00,GUNTAKAL,ANDHRA PRADESH,515801.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,544.00
16,16,406-9379318-6555504,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3721,JNE3721-KR-XXL,kurta,...,329.00,JAIPUR,RAJASTHAN,302020.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,0,None,None,329.00
17,17,405-9013803-8009918,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3405,JNE3405-KR-XL,kurta,...,399.00,NEW DELHI,DELHI,110074.0,IN,None,0,None,None,399.00
18,18,402-4030358-5835511,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3697,JNE3697-KR-XXL,kurta,...,458.00,Gurgaon,HARYANA,122004.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0,Easy Ship,None,458.00
19,19,405-5957858-1051546,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET254,SET254-KR-NP-XS,Set,...,886.00,BENGALURU,KARNATAKA,560017.0,IN,None,0,None,None,886.00

Task-3-SQL-Data-Analysis
├── Amazon Sale Report.csv
├── ecommerce_queries.sql
├── README.md
└── screenshots